name: Shared hello workflow

on:
  workflow_call:
    inputs:
      who:
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello ${{ inputs.who }} from reusable workflow vol2"